### ISSUE TITLE
OS_PROJECT_ID vs OS_TENANT_ID

### ISSUE THREAD

**Issue by StephaneBour** [sausin/laravel-ovh#73]
Hello,

I would like to know why the environment variable OS_TENANT_ID has been renamed to OS_PROJECT_ID, while it is still declared as OS_TENANT_ID in the downloadable file on OVH ?

Thank you.

**Comment by iksaku** [comment]
As far as I know, for the Openstack v3 documentation, you’re supposed to use `PROJECT_ID` for the specific containers that you’re using, since the `TENANT_ID` part may not be standardized yet.

I’ll take a look once more in Openstack’s documentation and with OVH’s downloadable files.

Thanks for the heads up 😄

**Comment by iksaku** [comment]
Sorry for the delay.

I've checked and can confirm that the new OVH's RC Files point to the new Keystone v3 environment variables. Maybe it'll be worth pointing that in the docs, to use v3 RC file.

![image](https://user-images.githubusercontent.com/4632429/95274615-e97edd00-080b-11eb-9c84-1584dbbb06d0.png)

At the time of this, #74 has been opened. I'll create a separate PR to indicate to use the v3 RC file, and let sausin choose if its worth mentioning both or just one of them :wink:

**Comment by iksaku** [comment]
Update, just checked in with OVH's traditional control panel. It seems to provide mixed values. So #74 will still be as important.

![image](https://user-images.githubusercontent.com/4632429/95276127-f8678e80-080f-11eb-8327-9e4e6db3ff10.png)

@sausin Could you merge #74? I'll also open a PR after it to provide steps for the Horizon panel.
